language: ruby
script: bundle exec rake test
sudo: false

rvm:
- "2.0"
- "2.1"
- "2.2"
- "2.3.1"

gemfile:
- Gemfile.activesupport32
- Gemfile.activesupport40
- Gemfile.activesupport41
- Gemfile.activesupport42

env:
  global:
  - ACTIVESHIPPING_NEW_ZEALAND_POST_KEY=4d9dc0f0-dda0-012e-066f-000c29b44ac0
  - ACTIVESHIPPING_CANADA_POST_LOGIN=CPC_DEMO_XML
  - ACTIVESHIPPING_CANADA_POST_PWS_CUSTOMER_NUMBER=2004381
  - ACTIVESHIPPING_CANADA_POST_PWS_API_KEY=6e93d53968881714
  - ACTIVESHIPPING_CANADA_POST_PWS_SECRET=0bfa9fcb9853d1f51ee57a
  - ACTIVESHIPPING_USPS_LOGIN=677JADED7283
  - ACTIVESHIPPING_UPS_LOGIN=shopifolk
  - ACTIVESHIPPING_UPS_KEY=7CE85DED4C9D07AB
  - ACTIVESHIPPING_UPS_PASSWORD=Shopify_rocks
  - ACTIVESHIPPING_UPS_ORIGIN_ACCOUNT=X3V606
  - ACTIVESHIPPING_UPS_ORIGIN_NAME=Shopify
